// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BannerBlock: typeof import('./src/components/home/BannerBlock.vue')['default']
    CopyrightBlock: typeof import('./src/components/general/CopyrightBlock.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FeaturedItem: typeof import('./src/components/home/FeaturedItem.vue')['default']
    FeaturedProperties: typeof import('./src/components/home/FeaturedProperties.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IBookingBathroom: typeof import('~icons/booking/bathroom')['default']
    IBookingBed: typeof import('~icons/booking/bed')['default']
    IBookingBookmarkButton: typeof import('~icons/booking/bookmark-button')['default']
    IBookingFacebookIcon: typeof import('~icons/booking/facebook-icon')['default']
    IBookingInstagramIcon: typeof import('~icons/booking/instagram-icon')['default']
    IBookingLinkedinIcon: typeof import('~icons/booking/linkedin-icon')['default']
    IBookingSearch: typeof import('~icons/booking/search')['default']
    IBookingSendIcon: typeof import('~icons/booking/send-icon')['default']
    IBookingTwitterIcon: typeof import('~icons/booking/twitter-icon')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LatestItem: typeof import('./src/components/home/LatestItem.vue')['default']
    LatestList: typeof import('./src/components/home/LatestList.vue')['default']
    MainFooter: typeof import('./src/components/general/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/general/MainHeader.vue')['default']
    NewsletterBlock: typeof import('./src/components/general/NewsletterBlock.vue')['default']
    ResultItem: typeof import('./src/components/search/ResultItem.vue')['default']
    ResultList: typeof import('./src/components/search/ResultList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBlock: typeof import('./src/components/home/SearchBlock.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
